# fly.toml app configuration file generated for staging-g-auth-5-9-24-1-1725540122-server on 2024-09-05T12:42:39Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'staging-g-auth-5-9-24-1-1725540122-server'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
